### ISSUE TITLE
Problem with files

### ISSUE THREAD

**Issue by MikeVL** [Parallels/docker-machine-parallels#30]
I create docker vm with overlay storage driver.

Very often, when installing programs via pip install inside vm, I get errors with inaccessible files.

```
Installing collected packages: Django, django-cacheback, django-gravatar2, newrelic, contextlib2, raven
  Found existing installation: Django 1.8.7
    Uninstalling Django-1.8.7:
      Successfully uninstalled Django-1.8.7
  Exception:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 246, in main
      status = self.run(options, args)
    File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 352, in run
      root=options.root_path,
    File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 704, in install
      requirement.commit_uninstall()
    File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 743, in commit_uninstall
      self.uninstalled.commit()
    File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 153, in commit
      rmtree(self.save_dir)
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
      return Retrying(*dargs, **dkw).call(f, *args, **kw)
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 212, in call
      raise attempt.get()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 247, in get
      six.reraise(self.value[0], self.value[1], self.value[2])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 200, in call
      attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 67, in rmtree
      onerror=rmtree_errorhandler)
    File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
      rmtree(fullname, ignore_errors, onerror)
    File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
      onerror(os.remove, fullname, sys.exc_info())
    File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 75, in rmtree_errorhandler
      if os.stat(path).st_mode & stat.S_IREAD:
  OSError: [Errno 2] No such file or directory: '/tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py
```
List of temporary folder:
```
root@1d1af6bf00a7:/opt/vluki# ls -la /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/
ls: cannot access /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py: No such file or directory
ls: cannot access /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/vary.py: No such file or directory
ls: cannot access /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/__init__.py: No such file or directory
ls: cannot access /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/debug.py: No such file or directory
ls: cannot access /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py: No such file or directory
ls: cannot access /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/gzip.py: No such file or directory
ls: cannot access /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/clickjacking.py: No such file or directory
ls: cannot access /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py: No such file or directory
total 8
d-w------- 2 root root 4096 Dec 15 07:48 .
drwxr-xr-x 4 root root 4096 Dec 15 07:48 ..
c????????? ? ?    ?       ?            ? cache.py
c????????? ? ?    ?       ?            ? clickjacking.py
c????????? ? ?    ?       ?            ? csrf.py
c????????? ? ?    ?       ?            ? debug.py
c????????? ? ?    ?       ?            ? gzip.py
c????????? ? ?    ?       ?            ? http.py
c????????? ? ?    ?       ?            ? __init__.py
c????????? ? ?    ?       ?            ? vary.py

root@1d1af6bf00a7:/opt/vluki# ls -la /tmp/pip-U_M5gO-uninstall/usr/local/lib/python2.7/dist-packages/django/views/
total 96
drwxr-xr-x  4 root root   4096 Dec 15 07:48 .
drwxr-xr-x 17 root root   4096 Dec 15 07:48 ..
-rw-r--r--  1 root staff  5057 Dec  7 08:38 csrf.py
-rw-r--r--  1 root staff 47451 Dec  7 08:38 debug.py
d-w-------  2 root root   4096 Dec 15 07:48 decorators
-rw-r--r--  1 root staff  2752 Dec  7 08:38 defaults.py
drwxr-xr-x  2 root root   4096 Dec 15 07:48 generic
-rw-r--r--  1 root staff 11043 Dec  7 08:38 i18n.py
-rw-r--r--  1 root staff     0 Dec  7 08:38 __init__.py
-rw-r--r--  1 root staff  5142 Dec  7 08:38 static.py
```

**Comment by legal90** [comment]
@MikeVL Could you please provide a reproduction instructions?

**Comment by legal90** [comment]
@MikeVL Is this issue still actual for you? It would be great to get some additional information which could help me to reproduce the issue.

**Comment by MikeVL** [comment]
I build docker container with
```
RUN pip install --no-cache-dir --compile -r requirements.txt
```
And, then, on running container i update some packages from requirements.txt i get this error.

**Comment by legal90** [comment]
@MikeVL I'm sorry, that's not enough for me to reproduce the issue. It would be good if you can describe how to run into this issue from the scratch.

I've tried to create a sample Django project with Docker Compose using this tutorial: https://docs.docker.com/compose/django/
Everything works fine for me. Could you tell which steps (exact commands) should be done after that to reproduce your issue?

**Comment by MikeVL** [comment]
My Dockerfile example
```
FROM debian:8.3

ADD requirements.txt /

RUN set -x \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        python-dev \
        python-pip \
    && pip install -r requirements.txt
```
and requirements.txt
```
Django<1.9
```
Build container and run:
```
➜  docker-test docker build -t test .
➜  docker-test docker run -it --rm test bash
root@0cb80b84f6c2:/# pip install "Django>1.9"
Downloading/unpacking Django>1.9
  Downloading Django-1.9.4-py2.py3-none-any.whl (6.6MB): 6.6MB downloaded
Installing collected packages: Django
  Found existing installation: Django 1.8.11
    Uninstalling Django:
      Successfully uninstalled Django
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1444, in install
    requirement.commit_uninstall()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 611, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1869, in commit
    rmtree(self.save_dir)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 45, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/pip-fZcZY8-uninstall/usr/local/bin'
```
Second run of pip install is ok
```
root@fdaa383b0c6c:/# pip install "Django>1.9"
Requirement already satisfied (use --upgrade to upgrade): Django>1.9 in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

**Comment by legal90** [comment]
@MikeVL Ah, thank you! Now it makes sense. It is reproducible only with "overlay" storage driver.

Seems like this is an issue of `overlayfs`. Please refer to https://github.com/docker/docker/issues/12327
There are some workarounds provided.

This issue is not related to the `parallels` driver for Docker Machine, so I close it.
